ALTER TABLE public.messages 
ADD COLUMN IF NOT EXISTS remote_msg_id TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS quoted_message_id UUID REFERENCES public.messages(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS quoted_content TEXT,
ADD COLUMN IF NOT EXISTS is_edited BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS reactions JSONB DEFAULT '{}'::jsonb;
