// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const safeStorage = {
  getItem: (key: string): string | null => {
    if (typeof window === 'undefined') return null;
    try {
      const val = localStorage.getItem(key);
      if (val !== null) return val;
    } catch {}
    try {
      return sessionStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem: (key: string, value: string): void => {
    if (typeof window === 'undefined') return;
    try {
      localStorage.setItem(key, value);
      return;
    } catch (e: any) {
      console.warn('[Supabase Storage] Failed to set item in localStorage:', key, e);
      if (
        e?.name === 'QuotaExceededError' ||
        e?.code === 22 ||
        e?.number === -2147024882 ||
        String(e).includes('QuotaExceededError') ||
        String(e).includes('quota')
      ) {
        console.warn('[Supabase Storage] Quota exceeded. Cleaning up non-essential cache...');
        try {
          localStorage.removeItem('ATENDI_QUERY_CACHE');
          const keysToRemove: string[] = [];
          for (let i = 0; i < localStorage.length; i++) {
            const k = localStorage.key(i);
            if (k && k !== key && !k.includes('selected_company') && !k.includes('selected_unit')) {
              keysToRemove.push(k);
            }
          }
          keysToRemove.forEach((k) => {
            try { localStorage.removeItem(k); } catch {}
          });
          localStorage.setItem(key, value);
          return;
        } catch (retryError) {
          console.warn('[Supabase Storage] Retry failed. Falling back to sessionStorage...', retryError);
          try {
            sessionStorage.setItem(key, value);
          } catch (sessionErr) {
            console.error('[Supabase Storage] Storage setItem failed in both localStorage and sessionStorage:', sessionErr);
          }
        }
      }
    }
  },
  removeItem: (key: string): void => {
    if (typeof window === 'undefined') return;
    try {
      localStorage.removeItem(key);
    } catch {}
    try {
      sessionStorage.removeItem(key);
    } catch {}
  },
};

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: safeStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

